steps:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml" "examples/vars.yml"
    when:
      - event: pull_request

  check_ansible_format:
    image: alpine:3
    commands:
      - export PATH=/root/.local/bin:$${PATH}
      - apk add pipx
      - pipx install --include-deps ansible
      - ansible-playbook lemmy.yml --syntax-check
      - ansible-playbook lemmy-almalinux.yml --syntax-check
      - ansible-playbook uninstall.yml --syntax-check
    when:
      - event: pull_request

  ansible_lint:
    image: alpine:3
    commands:
      - export PATH=/root/.local/bin:$${PATH}
      - apk add pipx
      - pipx install --include-deps ansible
      - pipx inject --include-deps ansible ansible-lint
      - ansible-lint --warn-list experimental lemmy.yml lemmy-almalinux.yml uninstall.yml examples/vars.yml
    when:
      - event: pull_request
