steps:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml" "examples/vars.yml"
    when:
      - event: pull_request

  check_ansible_format:
    image: pipelinecomponents/ansible-lint:0.79.11
    commands:
      - ansible-playbook lemmy.yml --syntax-check
      - ansible-playbook lemmy-almalinux.yml --syntax-check
      - ansible-playbook uninstall.yml --syntax-check
    when:
      - event: pull_request

  ansible_lint:
    image: pipelinecomponents/ansible-lint:0.79.11
    commands:
      - ansible-lint --warn-list experimental lemmy.yml lemmy-almalinux.yml uninstall.yml examples/vars.yml
    when:
      - event: pull_request
