pipeline:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml"
  check_ansible_format:
    image: alpine:3
    commands:
      - apk add ansible
      - ansible-playbook lemmy.yml --syntax-check
      - ansible-playbook lemmy-almalinux.yml --syntax-check
      - ansible-playbook uninstall.yml --syntax-check
