---
dependencies: []

galaxy_info:
  role_name: lemmy_backend
  author: dessalines
  description: Lemmy for linux
  license: "AGPL 3.0"
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - lemmy
    - fediverse
