---
dependencies: []

galaxy_info:
  role_name: pictrs_safety
  author: db0
  description: pictrs-safety for lemmy
  license: "AGPL 3.0"
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - lemmy
    - fediverse
    - pictrs
